name: dispatch workflow

on:
  workflow_dispatch:
    inputs:
      content:
        type: string
        description: 'string variable'
        required: true

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ inputs.content }} > content.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
