name: dispatch workflow

on:
  workflow_dispatch:
    inputs:
      content:
        type: string
        description: 'content'
        required: true

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ inputs.content }} >> content.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: run gh cli
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
